include(":vi-gradle-plugin", ":vi-api")
include(":startup:startup-gradle-plugin", ":startup:startup-api", ":startup:tasklist-composer")
include(":stability:breakpad")
include(":vi-lint-rules")
include(":apk:matrix-apk-canary")
include(":apk:matrix-arscutil")
include(":apk:matrix-commons")
